import { ResumeSpec } from '../schemas/resume.js';
import { PrivacyRulesConfig } from '../schemas/privacy.js';
import { redactText } from '../integrity/redaction-engine.js';

function redact(text: string, rules?: PrivacyRulesConfig): string {
  const effectiveRules: PrivacyRulesConfig = rules
    ? {
        strip_patterns: rules.strip_patterns ?? [],
        replacements: rules.replacements ?? [],
        banned_keywords: rules.banned_keywords ?? [],
      }
    : { strip_patterns: [], replacements: [], banned_keywords: [] };
  return redactText(text, effectiveRules).redactedText;
}

/**
 * Escapes characters that have special syntactic meaning in Typst markup mode.
 */
export function escapeTypst(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/([#$\[\]*_`<>"])/g, '\\$1');
}

function sanitizeUrl(url: string): string {
  const trimmed = url.trim();
  if (/^(?:javascript|vbscript|data|file|run):/i.test(trimmed)) {
    return '#';
  }
  if (!/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(trimmed)) {
    return `https://${trimmed}`;
  }
  return trimmed;
}

function redactAndEscape(text: string, rules?: PrivacyRulesConfig): string {
  return escapeTypst(redact(text, rules));
}

/**
 * Compiles a ResumeSpec into clean Typst source code (.typ)
 * with page setup, font configuration, and clean bullet formatting.
 */
export function compileTypstResume(spec: ResumeSpec, rules?: PrivacyRulesConfig): string {
  const name = redactAndEscape(spec.profile.name, rules);
  const title = redactAndEscape(spec.profile.title, rules);

  const contactItems: string[] = [];
  contactItems.push(redactAndEscape(spec.profile.email, rules));
  if (spec.profile.phone) {
    contactItems.push(redactAndEscape(spec.profile.phone, rules));
  }
  if (spec.profile.location) {
    contactItems.push(redactAndEscape(spec.profile.location, rules));
  }
  if (spec.profile.links) {
    for (const [, url] of Object.entries(spec.profile.links)) {
      if (url) {
        const cleanUrl = redact(url, rules);
        const safeUrl = sanitizeUrl(cleanUrl).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        const escapedUrl = escapeTypst(cleanUrl);
        contactItems.push(`#link("${safeUrl}")[${escapedUrl}]`);
      }
    }
  }

  const sections: string[] = [];

  // Preamble & Document setup
  sections.push(`// Generated by Featherduster
#set page(
  paper: "us-letter",
  margin: (x: 0.5in, y: 0.5in),
)

#set text(
  font: ("Source Sans Pro", "Liberation Sans", "Helvetica", "Arial"),
  size: 9.5pt,
)

#set par(justify: false, leading: 0.52em)

#show heading.where(level: 1): it => block(width: 100%, below: 0.6em)[
  #text(size: 10.5pt, weight: "bold")[#smallcaps(it.body)]
  #v(-0.35em)
  #line(length: 100%, stroke: 0.5pt + rgb("#9ca3af"))
]

#align(center)[
  #text(size: 18pt, weight: "bold")[${name}] \\
  #v(2pt)
  #text(size: 10.5pt)[${title}] \\
  #v(2pt)
  #text(size: 8.5pt, fill: rgb("#4b5563"))[
    ${contactItems.join(' | ')}
  ]
]`);

  // Summary
  if (spec.summary && spec.summary.trim()) {
    const cleanSummary = redactAndEscape(spec.summary, rules);
    sections.push(`= Summary\n${cleanSummary}`);
  }

  // Experience
  if (spec.experiences && spec.experiences.length > 0) {
    const expBlocks = spec.experiences.map((exp) => {
      const company = redactAndEscape(exp.company, rules);
      const role = redactAndEscape(exp.role, rules);
      const location = exp.location ? redactAndEscape(exp.location, rules) : '';
      const dateLoc = location
        ? `${escapeTypst(exp.startDate)} -- ${escapeTypst(exp.endDate)} | ${location}`
        : `${escapeTypst(exp.startDate)} -- ${escapeTypst(exp.endDate)}`;

      const bulletLines = exp.bullets
        .map((b) => `- ${redactAndEscape(b.text, rules)}`)
        .join('\n');

      return `*${role}*, ${company} #h(1fr) ${dateLoc}\n${bulletLines}`;
    });

    sections.push(`= Experience\n\n${expBlocks.join('\n\n')}`);
  }

  // Education
  if (spec.education && spec.education.length > 0) {
    const eduBlocks = spec.education.map((edu) => {
      const institution = redactAndEscape(edu.institution, rules);
      const degree = redactAndEscape(edu.degree, rules);
      const details = edu.details ? redactAndEscape(edu.details, rules) : '';
      const year = escapeTypst(String(edu.year));

      let line = `*${degree}*, ${institution} #h(1fr) ${year}`;
      if (details) {
        line += `\n_${details}_`;
      }
      return line;
    });

    sections.push(`= Education\n\n${eduBlocks.join('\n\n')}`);
  }

  // Skills
  if (spec.skills && spec.skills.length > 0) {
    const skillLines = spec.skills.map((g) => {
      const cat = redactAndEscape(g.category, rules);
      const list = g.skills.map((s) => redactAndEscape(s, rules)).join(', ');
      return `- *${cat}:* ${list}`;
    });

    sections.push(`= Skills\n\n${skillLines.join('\n')}`);
  }

  return sections.join('\n\n').trim() + '\n';
}
